#!/bin/bash

#import ipynb_py_convert
ipynb-py-convert nhsd_docker_pyspark_package/FacadeFunctions.py nhsd_databricks_package/FacadeFunctions.ipynb

ipynb-py-convert nhsd_docker_pyspark_package/ParentPhenoClasses.py nhsd_databricks_package/ParentPhenoClasses.ipynb

ipynb-py-convert nhsd_docker_pyspark_package/DateBasedPhenoFunctions.py nhsd_databricks_package/DateBasedPhenoFunctions.ipynb